
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://scout_user:scout_pass@db:5432/baseball_scouting
      - NODE_ENV=production
      - SESSION_SECRET=your-super-secure-session-secret-here
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=baseball_scouting
      - POSTGRES_USER=scout_user
      - POSTGRES_PASSWORD=scout_pass
    ports:
      - "5432:5432"
    volumes:
      # Mount to host directory for easier backups
      - /var/lib/baseball-scouting/data:/var/lib/postgresql/data
      - /var/lib/baseball-scouting/backups:/backups
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local